### ISSUE TITLE
Red Intellisense on latest Mac osx not working. How to fix it?

### ISSUE THREAD

**Issue by HFolkertH** [red/VScode-extension#16]
it keeps on saying "loading......"  but nothing happens.

**Comment by munael** [comment]
Same on Windows 8.1 with VS Code 1.14.

Some things do have tooltips but very basic ones. Like
```red
is a word! value: View
```
and such.

Or `image` in the view dialect showing `image!`.

But mostly it just says `Loading...`. Definitely no documentation showing in the tooltips as in the examples gifs.

**Comment by senritsu** [comment]
Same for windows 10 x64 with VS Code 1.19.2

Only ever get things like `is a word! value: sort`, no documentation or anything.

**Comment by iceflow19** [comment]
@senritsu @Enamex  I've opened a pull request to fix the intellisense on words defined by Red. Anything else will show a "Loading..." which from what I can gather from the code, is the intended behavior. Perhaps a new issue should be opened to address improving that behavior?

**Comment by qtxie** [comment]
> Anything else will show a "Loading..." which from what I can gather from the code, is the intended behavior.

@iceflow19 Do you know how to remove it? I'm not familiar with Javascript and Typescript. It will be great help if you can improve the plugin.

**Comment by iceflow19** [comment]
@qtxie That assessment was based on just my cursory reading of the code. I'd have to look at it further in depth.

Typescript is one of the primary languages we use in-house at my startup company. My startup consumes alot of my time. The only reason I fixed this was because I was going to do some coding in Red for my Masters Thesis. If I find some more free time, I'll see if I cant do a few more improvements/debugging.
